[project]

site_name = "cheatsheets"
site_description = ""
site_author = "sonnytricky"
# site_url = "https://www.example.com/"

copyright = "© 2026 sonnytricky"

repo_name = "sonnytricky/cheatsheets"
repo_url = "https://github.com/sonnytricky/cheatsheets"

edit_uri = "edit/main/docs/"

docs_dir = "docs"
site_dir = "site"


# ----------------------------------------------------------------------------
# navigation
# ----------------------------------------------------------------------------

nav = [
  {"Get started" = "index.md"},
  {"GIT" = [
     "git/index.md",
     "git/Ordner_zur_Repo_machen.md" 
  ]},
  {"Markdown" = "markdown/markdown.md"}  
]

# ----------------------------------------------------------------------------
# css und javascript
# ----------------------------------------------------------------------------

#extra_css = ["stylesheets/extra.css"]                                      # der Ordner wurden bereits angelegt
#extra_javascript = ["javascripts/extra.js"]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------

[project.theme]
#variant = "classic"                                                        # classic = mklook

#custom_dir = "overrides"                                                   # in diesem ordner kann man die zensical HTML-vorlagen überschreiben, ist auch für die bootstrap-logos

favicon = "images/favicon.png"                                              # der image ordner muss in docs/ sein
logo = "assets/logo.png"                                                    # der assets ordner muss in den docs/sein
language = "de"                                                             # war auf "en"

# ----------------------------------------------------------------------------
# features
# ----------------------------------------------------------------------------
features = [
    # Zensical includes an announcement bar. This feature allows users to
    # dismiss it when they have read the announcement.
    # https://zensical.org/docs/setup/header/#announcement-bar
    "announce.dismiss",

#    "content.action.edit",                                                  # Edit this page on github  # es muss dann noch -> unter [projekt] edit_uri = "edit/main/docs/" stehen

    "content.action.view",                                                  # View source of this page on github

    # Code annotations allow you to add an icon with a tooltip to your
    # code blocks to provide explanations at crucial points.
    # https://zensical.org/docs/authoring/code-blocks/#code-annotations
    "content.code.annotate",

    "content.code.copy",                                                     # copy button

#    "content.code.select",

    # Zensical can render footnotes as inline tooltips, so the user can read
    # the footnote without leaving the context of the document.
    # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
    "content.footnote.tooltips",

    # If you have many content tabs that have the same titles (e.g., "Python",
    # "JavaScript", "Cobol"), this feature causes all of them to switch to
    # at the same time when the user chooses their language in one.
    # https://zensical.org/docs/authoring/content-tabs/#linked-content-tabs
    "content.tabs.link",

    # With this feature enabled users can add tooltips to links that will be
    # displayed when the mouse pointer hovers the link.
    # https://zensical.org/docs/authoring/tooltips/#improved-tooltips
    "content.tooltips",

    # With this feature enabled, Zensical will automatically hide parts
    # of the header when the user scrolls past a certain point.
    # https://zensical.org/docs/setup/header/#automatic-hiding
    # "header.autohide",

#   "navigation.expand",                                                   # Navigaion ausgeklappt

    "navigation.footer",

    "navigation.indexes",                                                 # Inhaltsverzeichnisseiten

    "navigation.instant",                                                 # Vorladen der Seiten

    "navigation.instant.prefetch",                                         # Sofortiges Vorladen

#   "navigation.instant.progress",                                         # Fortschritsanzeige

    "navigation.path",                                                      # es steht dann oben der Pfad 

#   "navigation.prune",                                                    # ob der Text scrollt oder nicht

#   "navigation.sections",                                                 # Navigationsabschnitte

#   "navigation.tabs",                                                     # tabs in der Header leiste

    "navigation.tabs.sticky",                                               # linke seitenleiste immer sichtbar

    "navigation.top",                                                       # back-to-top button

    "navigation.tracking",                                                  # Ankerverfolgung der Überschriften

    "search.highlight",

    "toc.follow",                                                           # verfolgt die Überschriften

#    "toc.integrate",                                                       # Inhaltsverzeichnis in den Überschriften
]

# ---------------------------------------------------------------------------

#[project.theme.icon]
#logo = "lucide/smile"

#[project.theme.font]                                                         # ändert die Schriftart
#text = "Inter"                                                               # ändert die Schriftart
#code = "Jetbrains Mono"                                                      # ändert die Schriftart

# --------------------------------------------------------------------------- 
# Hell und Dunkel modus und deren icons
# --------------------------------------------------------------------------- 

[[project.theme.palette]]                                                      
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

primary = "indigo"                                                            # red pink purple deep purple indigo blue light blue cyan teal green light green lime yellow amber orange deep orange brown grey blue grey black white
accent = "orange"                                                             # red pink purple deep purple indigo blue light blue cyan teal green light green lime yellow amber orange deep orange

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------

# ---------- Soziale Medien

# GitHub
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/sonnytricky"
name = "sonnytricky on GitHub"

# Instagram
[[project.extra.social]]
icon = "fontawesome/brands/instagram"
link = "https://www.instagram.com/sonnytricky/"
name = "sonnytricky on Instagram"

# ---------- Footer

[project.extra]
generator = false


